trigger:
  branches:
    include:
      - master
      - dev_0.22

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    linux-package:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: |
      set -e
      sudo apt-get update
      sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0
      sudo cp .azure-pipelines/xvfb.init /etc/init.d/xvfb
      sudo chmod +x /etc/init.d/xvfb
      sudo update-rc.d xvfb defaults
      sudo service xvfb start
    displayName: Setup Xvfb
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - task: SonarCloudPrepare@1
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))
    inputs:
      SonarCloud: "sonarcloud"
      organization: "prb28-github"
      scannerMode: "CLI"
      configMode: "file"

  - task: Npm@1
    inputs:
      command: "install"

  - bash: |
      echo ">>> Package"
      npm install -g vsce
      npm run coverage:disable
      vsce package
      cp *.vsix $(Build.ArtifactStagingDirectory)
    displayName: Package
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux-package'))

  - bash: |
      echo ">>> Compile vscode-test"
      npm run vscode:prepublish
      npm run test:coverage
      npm run tslint
    displayName: Run Tests
    condition: and(succeeded(), and(ne(variables['Agent.JobName'], 'Job linux-package'), ne(variables['Agent.JobName'], 'Job linux')))

  - bash: |
      echo ">>> Compile vscode-test"
      npm run vscode:prepublish
      xvfb-run --auto-servernum --server-args='-screen 0, 1280x960x24' npm run test:coverage
      npm run tslint
    displayName: Run Tests
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: "out/**/test-results.xml"
    condition: and(succeededOrFailed(), eq(variables['Agent.JobName'], 'Job linux'))

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))

  - bash: |
      echo ">>> Publish to coveralls"
      node_modules/.bin/coveralls < coverage/lcov.info
    displayName: Publish to Coveralls
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux-package'))
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "extension"
      publishLocation: "Container"

  - task: SonarCloudAnalyze@1
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: "300"
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Job linux'))
